In [1]:
# -*- coding:utf-8 -*-
### 第一部分 ###：数据探索分析——网页类型分析

import pandas as pd
from sqlalchemy import create_engine

# 先自定义函数将表格写入数据库里，以备操作过程中有些数据要写入数据库
def savetosql(DF,tablename):
    import pandas as pd
    from sqlalchemy import create_engine
    yconnect = create_engine('mysql+mysqldb://root:@127.0.0.1:3306/jing?charset=utf8')  
    pd.io.sql.to_sql(DF,tablename, yconnect, schema='jing', if_exists='append')

In [2]:
# python 访问数据库
engine = create_engine('mysql+pymysql://root:@127.0.0.1:3306/jing?charset=utf8')
sql = pd.read_sql('all_gzdata', engine, chunksize = 10000)
# '''
# 由于本人电脑用的主机Host名称为：127.0.0.1，端口3306，使用的数据库名称为test,字符集为utf8，用户名为root,密码为空,所以配置如上所示
# 用create_engine建立连接，连接地址的意思依次为“数据库格式（mysql）+程序名（pymysql）+账号密码@地址端口/数据库名（test）”，最后指定编码为utf8；
# all_gzdata是表名，engine是连接数据的引擎，chunksize指定每次读取1万条记录。这时候sql是一个容器，未真正读取数据。

# '''
# realIP`, `realAreacode`, `userAgent`, `userOS`, 
# `userID`, `clientID`, `timestamp`, `timestamp_format`,
# `pagePath`, `ymd`, `fullURL`, `fullURLId`, `hostname`, 
# `pageTitle`, `pageTitleCategoryId`, `pageTitleCategoryName`,
# `pageTitleKw`, `fullReferrer`, `fullReferrerURL`, `organicKeyword`, `source`

#-----* 1 *----- 统计各个网页类型所占的比例

counts1 = [ i['fullURLId'].value_counts() for i in sql] #逐块统计
counts1

D:\Anaconda2\lib\site-packages\pymysql-0.7.11-py2.7.egg\pymysql\cursors.py:165: Warning: (1366, u"Incorrect string value: '\\xD6\\xD0\\xB9\\xFA\\xB1\\xEA...' for column 'VARIABLE_VALUE' at row 480")
  result = self._query(query)

[101003     4762
 1999001    2389
 107001     2143
 301001      177
 101002      166
 102002      163
 101001       51
 106001       37
 103003       26
 101009       18
 103002       15
 102001       15
 102005       10
 101008        8
 102003        6
 102008        4
 101007        3
 102006        2
 102009        2
 101005        1
 101004        1
 101006        1
 Name: fullURLId, dtype: int64, 101003     4832
 107001     2306
 1999001    2269
 301001      154
 102002      151
 101002      134
 101001       53
 106001       40
 102001       14
 103003       11
 102003        8
 101009        6
 103002        5
 102005        4
 102006        3
 101006        3
 101008        3
 102007        2
 102004        1
 101004        1
 Name: fullURLId, dtype: int64, 101003     4755
 107001     2314
 1999001    2104
 102002      239
 301001      184
 101002      163
 101001       64
 106001       52
 102001       33
 102003       24
 103003       23
 102005       12
 101009       11
 102004        8
 102008        4
 101006        4
 102006        2
 101008        2
 101005        1
 101007        1
 Name: fullURLId, dtype: int64, 101003     4462
 107001     2426
 1999001    2422
 102002      202
 301001      192
 101001       90
 101002       58
 106001       56
 103003       32
 102003       18
 102001       12
 102008        7
 102005        6
 101009        6
 101008        3
 102007        2
 103002        2
 102009        2
 101004        1
 101006        1
 Name: fullURLId, dtype: int64, 101003     4366
 1999001    2593
 107001     2276
 301001      235
 102002      222
 101002       80
 106001       63
 101001       49
 103003       37
 102001       21
 102003       14
 102006        7
 101009        7
 102005        5
 103002        5
 102008        4
 101005        3
 101006        3
 101008        3
 102007        2
 102009        2
 102004        2
 101004        1
 Name: fullURLId, dtype: int64, 101003     4385
 1999001    2689
 107001     2164
 102002      273
 301001      151
 106001       72
 103003       69
 101001       65
 101002       62
 102003       16
 101009       15
 102001       14
 103002        5
 102009        5
 102004        4
 102007        4
 101008        3
 102008        1
 101005        1
 101004        1
 101006        1
 Name: fullURLId, dtype: int64, 101003     4709
 107001     2412
 1999001    2173
 301001      211
 102002      176
 106001       87
 101001       68
 101002       43
 103003       38
 102001       28
 102003       11
 102005       11
 101009       10
 102004        8
 101008        6
 102009        6
 101006        2
 102008        1
 Name: fullURLId, dtype: int64, 101003     4629
 1999001    2521
 107001     2273
 301001      207
 102002      174
 101001       43
 106001       39
 101002       28
 102001       19
 102003       15
 103003       12
 102007        7
 102004        6
 101009        6
 101008        5
 102005        4
 102006        4
 102008        4
 103002        3
 101006        1
 Name: fullURLId, dtype: int64, 101003     4473
 1999001    2459
 107001     2257
 102002      220
 301001      218
 106001      164
 101001       62
 101002       33
 103003       31
 102001       26
 102003       15
 102009       14
 101004        7
 101009        6
 102007        4
 103002        4
 102005        2
 101007        2
 101006        2
 101008        1
 Name: fullURLId, dtype: int64, 101003     4608
 1999001    2418
 107001     2399
 301001      188
 102002      144
 101002       67
 101001       62
 106001       50
 103003       20
 102001       11
 101009       11
 102003        8
 102007        6
 102005        2
 102006        2
 101007        2
 103002        1
 101004        1
 Name: fullURLId, dtype: int64, 101003     4506
 1999001    2586
 107001     2289
 102002      193
 301001      191
 101002       78
 106001       42
 101001       37
 103003       24
 102001       17
 101009       12
 102003       10
 102008        6
 101007        3
 102007        2
 101008        2
 101004        1
 101006        1
 Name: fullURLId, dtype: int64, 101003     4779
 1999001    2407
 107001     2177
 102002      155
 101002      147
 301001      147
 106001       53
 101001       44
 102001       32
 103003       13
 101009        9
 102003        7
 101008        5
 102007        4
 101007        4
 102006        4
 102008        4
 102009        2
 103002        2
 102005        2
 102004        1
 101004        1
 101006        1
 Name: fullURLId, dtype: int64, 101003     4617
 1999001    2436
 107001     2345
 301001      174
 101002      124
 102002      104
 101001       56
 106001       44
 102001       31
 103003       21
 102003       12
 101009       11
 102006        6
 101008        6
 102008        4
 102007        2
 102004        2
 103002        2
 101007        1
 101006        1
 101004        1
 Name: fullURLId, dtype: int64, 101003     4674
 1999001    2366
 107001     2135
 102002      248
 301001      242
 101002      184
 101001       36
 106001       30
 102001       26
 103003       14
 101009       11
 102003       10
 102004        6
 102008        6
 101007        4
 101006        3
 102006        2
 101008        2
 101004        1
 Name: fullURLId, dtype: int64, 101003     4605
 1999001    2365
 107001     2262
 301001      219
 102002      213
 101002      157
 101001       53
 106001       31
 102003       22
 103003       19
 102001       17
 101009       11
 103002        6
 102008        4
 102004        3
 102007        2
 102009        2
 102006        2
 102005        2
 101004        2
 101008        2
 101007        1
 Name: fullURLId, dtype: int64, 101003     4758
 1999001    2470
 107001     2091
 102002      189
 301001      159
 101002      134
 101001       49
 106001       48
 102003       24
 102001       22
 103003       18
 101009        7
 102007        6
 102005        5
 101007        5
 102004        4
 102006        4
 101008        3
 101006        2
 101005        1
 101004        1
 Name: fullURLId, dtype: int64, 101003     4850
 1999001    2347
 107001     1992
 301001      211
 102002      204
 101002      161
 101001       70
 106001       41
 102001       28
 103003       24
 102003       23
 101004        9
 102008        8
 101009        7
 101005        5
 102006        4
 102007        4
 101007        3
 101008        2
 103002        2
 102005        2
 102009        2
 101006        1
 Name: fullURLId, dtype: int64, 101003     4817
 1999001    2260
 107001     2247
 301001      253
 102002      150
 106001       62
 101002       60
 101001       60
 102001       18
 102003       14
 102004       10
 101009       10
 102008       10
 103003        8
 102007        6
 102005        6
 102006        3
 101007        2
 101008        2
 101005        1
 101006        1
 Name: fullURLId, dtype: int64, 101003     4652
 1999001    2391
 107001     2235
 301001      341
 102002      122
 101002       81
 101001       63
 106001       42
 102001       22
 103003       19
 101009       14
 102003        8
 101008        3
 102006        2
 102008        2
 101004        2
 101007        1
 Name: fullURLId, dtype: int64, 101003     4692
 1999001    2350
 107001     2193
 301001      325
 102002      122
 101001       81
 101002       69
 106001       50
 103003       31
 102001       27
 102003       12
 102009       10
 101007        9
 101009        8
 102007        4
 101008        4
 101005        3
 101004        3
 101006        3
 102005        2
 102008        2
 Name: fullURLId, dtype: int64, 101003     4589
 1999001    2542
 107001     2032
 301001      390
 102002      139
 101001       82
 101002       64
 106001       52
 103003       22
 102001       19
 103002       13
 102003       11
 101009       10
 102007        8
 102005        6
 102008        6
 101008        5
 102006        4
 102004        2
 101007        2
 101005        1
 101006        1
 Name: fullURLId, dtype: int64, 101003     4640
 1999001    2412
 107001     2292
 301001      203
 102002      128
 101002      121
 106001       52
 101001       50
 103003       26
 102001       22
 102003       16
 101009       12
 103002        8
 102008        5
 101008        5
 102007        4
 102004        2
 102006        2
 Name: fullURLId, dtype: int64, 101003     4356
 107001     2455
 1999001    2409
 301001      227
 102002      220
 101002       91
 101001       61
 106001       52
 103003       41
 103002       17
 101009       14
 102003       12
 102001       12
 101008        9
 102007        8
 102005        3
 102008        3
 101004        3
 101006        3
 101007        2
 102009        1
 101005        1
 Name: fullURLId, dtype: int64, 101003     4509
 107001     2470
 1999001    2340
 301001      189
 102002      164
 101001       83
 101002       75
 106001       57
 103003       25
 102001       21
 101009       13
 102003       10
 103002        8
 102009        8
 102007        8
 102008        5
 102006        4
 102005        4
 101008        4
 102004        2
 101007        1
 Name: fullURLId, dtype: int64, 101003     4870
 107001     2239
 1999001    2220
 301001      235
 102002      138
 101001       67
 101002       50
 102001       44
 106001       37
 102003       23
 103003       13
 102004       12
 101009       12
 102007       10
 103002        9
 101008        7
 102006        6
 102005        4
 101004        2
 101007        2
 Name: fullURLId, dtype: int64, 101003     4719
 1999001    2441
 107001     2137
 301001      202
 102002      174
 101002      121
 101001       64
 106001       49
 102001       23
 102003       15
 103003       12
 102006        8
 101009        8
 102005        6
 102004        5
 102007        4
 101007        2
 102009        2
 101005        2
 102008        2
 101004        1
 101006        1
 101008        1
 103002        1
 Name: fullURLId, dtype: int64, 101003     4485
 1999001    2538
 107001     2250
 101002      196
 301001      181
 102002      125
 101001       79
 106001       49
 102001       20
 101009       19
 103003       14
 102003       13
 101008        7
 102008        4
 102004        4
 103002        4
 101007        3
 102007        2
 102006        2
 101004        2
 102009        2
 101006        1
 Name: fullURLId, dtype: int64, 101003     4551
 1999001    2450
 107001     2220
 301001      250
 102002      183
 101002      144
 101001       59
 103003       34
 106001       33
 102001       24
 102008       12
 101009       10
 102003        7
 102007        6
 103002        5
 102006        4
 102005        2
 102004        2
 101005        1
 101004        1
 101007        1
 101008        1
 Name: fullURLId, dtype: int64, 101003     4630
 1999001    2382
 107001     2373
 301001      208
 102002      159
 101002       96
 101001       61
 103003       25
 106001       24
 101009       14
 102001       13
 102003        8
 102004        2
 102007        2
 102008        2
 101005        1
 Name: fullURLId, dtype: int64, 101003     4605
 1999001    2350
 107001     2278
 301001      290
 102002      190
 101002       94
 101001       75
 106001       38
 102001       26
 103003       10
 102003        8
 102008        6
 102007        6
 102004        6
 101009        6
 102005        4
 101004        3
 102009        2
 101005        1
 101006        1
 101008        1
 Name: fullURLId, dtype: int64, 101003     4345
 1999001    2618
 107001     2298
 301001      278
 102002      173
 101001       95
 101002       77
 106001       37
 102001       24
 103003       17
 101009       10
 102003        6
 102006        6
 102004        4
 101008        4
 102005        2
 102008        2
 102009        2
 101007        1
 101006        1
 Name: fullURLId, dtype: int64, 101003     4653
 1999001    2308
 107001     2188
 301001      235
 102002      229
 101002      157
 101001       73
 106001       57
 102001       29
 103003       17
 102003       16
 101009       12
 102007        8
 101008        6
 102005        3
 102004        2
 101007        2
 102006        1
 103002        1
 101005        1
 101004        1
 101006        1
 Name: fullURLId, dtype: int64, 101003     4899
 1999001    2419
 107001     2007
 301001      177
 102002      141
 101002      136
 101001       79
 106001       48
 102001       32
 102003       17
 103003        9
 101009        7
 102005        6
 102008        5
 102004        4
 101008        4
 103002        3
 101007        3
 102006        2
 101004        2
 Name: fullURLId, dtype: int64, 101003     4901
 1999001    2294
 107001     2184
 301001      203
 102002      121
 101002      121
 101001       73
 106001       28
 102001       25
 103003       15
 102003        9
 101009        9
 102005        4
 101008        4
 102004        2
 102006        2
 102008        2
 102007        2
 101007        1
 Name: fullURLId, dtype: int64, 101003     4743
 1999001    2480
 107001     1927
 301001      255
 102002      160
 101002      104
 101001      102
 106001       53
 103003       46
 102001       23
 101008       21
 101009       16
 102003       13
 102007       12
 103002       11
 102008        7
 102005        7
 101007        6
 101005        4
 102006        3
 101004        2
 102004        2
 102009        2
 101006        1
 Name: fullURLId, dtype: int64, 101003     4697
 1999001    2426
 107001     2186
 102002      211
 301001      147
 101002       71
 101001       65
 106001       53
 102001       34
 103003       32
 102007       29
 101009       14
 102003        9
 102008        9
 102004        7
 102006        4
 102005        3
 101004        2
 101006        1
 Name: fullURLId, dtype: int64, 101003     4421
 1999001    2494
 107001     2230
 102002      224
 301001      171
 102007      116
 101002      100
 101001       72
 106001       53
 102001       35
 103003       25
 101009       16
 102003       10
 101008       10
 103002        8
 102004        4
 102005        4
 101006        3
 101007        2
 101005        1
 101004        1
 Name: fullURLId, dtype: int64, 101003     4720
 1999001    2488
 107001     1968
 301001      242
 101002      152
 102002      148
 101001       86
 102007       60
 103003       38
 106001       27
 101009       19
 102001       19
 101008        8
 102003        6
 102008        6
 101004        4
 103002        3
 101006        3
 101005        2
 101007        1
 Name: fullURLId, dtype: int64, 101003     4669
 1999001    2611
 107001     1992
 301001      222
 102002      123
 101002      108
 101001       79
 106001       50
 102001       45
 103003       35
 102003       12
 102008       11
 102007        8
 101009        8
 102004        7
 101006        5
 101008        5
 102006        3
 102005        3
 101005        2
 101004        2
 Name: fullURLId, dtype: int64, 101003     4738
 1999001    2376
 107001     2200
 301001      247
 102002      129
 101002      102
 101001       45
 106001       41
 102001       34
 103003       22
 102003       19
 102004       12
 101009       10
 102008        8
 101008        5
 102005        4
 102006        2
 102007        2
 101004        2
 101006        2
 Name: fullURLId, dtype: int64, 101003     4820
 1999001    2385
 107001     2186
 301001      163
 102002      153
 101002       83
 101001       64
 102001       40
 106001       32
 102003       24
 101009       10
 103003       10
 102006        6
 102004        6
 102009        6
 102008        5
 102005        2
 101006        2
 101005        1
 101004        1
 101008        1
 Name: fullURLId, dtype: int64, 101003     4850
 1999001    2380
 107001     2136
 301001      218
 102002      117
 101002      113
 101001       56
 106001       39
 102001       22
 102003       17
 103003       12
 101009        9
 102008        6
 102004        4
 101004        4
 101008        4
 102006        3
 102005        2
 102007        2
 101005        2
 101007        2
 101006        2
 Name: fullURLId, dtype: int64, 101003     4822
 1999001    2343
 107001     2282
 301001      172
 102002      151
 101001       57
 101002       52
 106001       44
 102001       24
 101009       16
 102003       13
 102007        8
 103003        7
 102005        2
 102008        2
 101006        2
 102009        2
 101004        1
 Name: fullURLId, dtype: int64, 101003     5116
 1999001    2233
 107001     2088
 301001      236
 102002      103
 101001       53
 101002       38
 102001       29
 106001       28
 102003       12
 102007       10
 101009        9
 102006        8
 103003        8
 102004        6
 102009        6
 102008        4
 102005        4
 101008        4
 101004        2
 101007        2
 101006        1
 Name: fullURLId, dtype: int64, 101003     5063
 1999001    2448
 107001     1907
 301001      212
 102002      158
 101001       52
 101002       48
 106001       30
 102003       15
 103003       14
 102001       13
 101008       12
 101009       10
 102007        8
 102005        4
 102004        2
 102008        2
 103002        1
 101006        1
 Name: fullURLId, dtype: int64, 101003     5222
 1999001    2305
 107001     1912
 301001      157
 102002      117
 106001       60
 103003       52
 101001       52
 101002       36
 102001       20
 103002       14
 101009        9
 101008        9
 102003        9
 102007        6
 101007        5
 102008        5
 102005        4
 102006        2
 102004        2
 101004        1
 101006        1
 Name: fullURLId, dtype: int64, 101003     5092
 1999001    2576
 107001     1786
 301001      196
 101002       95
 102002       73
 101001       57
 106001       47
 103003       25
 102003       10
 102001        9
 101009        9
 102009        6
 102005        4
 102007        4
 102008        4
 102006        2
 102004        2
 101004        1
 101006        1
 101008        1
 Name: fullURLId, dtype: int64, 101003     4981
 107001     2233
 1999001    2191
 301001      187
 102002      148
 101002       59
 101001       51
 106001       43
 102001       26
 102003       23
 103003       18
 102005        8
 102004        8
 101009        8
 102007        4
 102008        3
 102006        2
 101007        2
 101006        2
 101008        2
 101004        1
 Name: fullURLId, dtype: int64, 101003     5108
 1999001    2206
 107001     2178
 301001      177
 102002       94
 101001       75
 101002       63
 106001       33
 102001       23
 102003       10
 103003        8
 101009        6
 101006        4
 102009        4
 101007        2
 102008        2
 102007        2
 102004        2
 101004        1
 101008        1
 103002        1
 Name: fullURLId, dtype: int64, 101003     4813
 107001     2287
 1999001    2245
 301001      264
 102002      117
 101002       76
 101001       62
 106001       39
 102001       24
 102007       20
 102003       17
 101009        9
 102008        5
 102004        5
 103003        5
 102005        4
 101005        2
 101006        2
 102009        2
 101004        1
 101007        1
 Name: fullURLId, dtype: int64, 101003     4618
 1999001    2475
 107001     2277
 301001      213
 101002      121
 102002      117
 101001       62
 106001       40
 102003       25
 102001       22
 101009       10
 102008        6
 103003        5
 102009        4
 102007        2
 101004        2
 101008        1
 Name: fullURLId, dtype: int64, 101003     4803
 1999001    2366
 107001     2168
 301001      197
 102002      113
 101002       99
 101001       95
 102001       47
 106001       36
 102003       20
 103003       17
 102004       13
 101008        7
 102008        6
 101009        6
 101004        3
 102007        2
 101007        2
 Name: fullURLId, dtype: int64, 101003     4704
 1999001    2503
 107001     2204
 301001      135
 102002      134
 101002       85
 101001       77
 102001       32
 106001       29
 103003       22
 101008       19
 102003       16
 101009       16
 102007        8
 102008        8
 101007        3

In [3]:
counts1 = pd.concat(counts1).groupby(level=0).sum() #合并统计结果，把相同的统计项合并（即按index分组并求和）
counts1

101001       5603
101002       7776
101003     396612
101004        125
101005         63
101006        107
101007        147
101008        378
101009        854
102001       2129
102002      12021
102003       1235
102004        361
102005        271
102006        184
102007        538
102008        404
102009        214
103002        189
103003       1526
106001       3957
107001     182900
1999001    201426
301001      18430
Name: fullURLId, dtype: int64

In [4]:
counts1 = counts1.reset_index() #重新设置index，将原来的index作为counts的一列。
counts1

      index  fullURLId
0    101001       5603
1    101002       7776
2    101003     396612
3    101004        125
4    101005         63
5    101006        107
6    101007        147
7    101008        378
8    101009        854
9    102001       2129
10   102002      12021
11   102003       1235
12   102004        361
13   102005        271
14   102006        184
15   102007        538
16   102008        404
17   102009        214
18   103002        189
19   103003       1526
20   106001       3957
21   107001     182900
22  1999001     201426
23   301001      18430

In [5]:
counts1.columns = ['index', 'num'] #重新设置列名，主要是第二列，默认为0
counts1['type'] = counts1['index'].str.extract('(\d{3})') #提取前三个数字作为类别id（！！！）
counts1

D:\Anaconda2\lib\site-packages\ipykernel_launcher.py:2: FutureWarning: currently extract(expand=None) means expand=False (return Index/Series/DataFrame) but in a future version of pandas this will be changed to expand=True (return DataFrame)

      index     num type
0    101001    5603  101
1    101002    7776  101
2    101003  396612  101
3    101004     125  101
4    101005      63  101
5    101006     107  101
6    101007     147  101
7    101008     378  101
8    101009     854  101
9    102001    2129  102
10   102002   12021  102
11   102003    1235  102
12   102004     361  102
13   102005     271  102
14   102006     184  102
15   102007     538  102
16   102008     404  102
17   102009     214  102
18   103002     189  103
19   103003    1526  103
20   106001    3957  106
21   107001  182900  107
22  1999001  201426  199
23   301001   18430  301

In [6]:
counts1_ = counts1[['type', 'num']].groupby('type').sum() #按类别合并
counts1_.sort_values(by='num', ascending=False,inplace=True) #降序排列
counts1_['percentage'] = (counts1_['num']/counts1_['num'].sum())*100

#保存的表名命名格式为“1_1_k此表功能名称”，此表表示生成的第1张表格，功能为type_counts：计算各个大类占的比例
counts1_.to_excel('1_1_1type_counts.xlsx') 
counts1_

         num  percentage
type
101   411665   49.156965
199   201426   24.052302
107   182900   21.840110
301    18430    2.200728
102    17357    2.072601
106     3957    0.472506
103     1715    0.204788

In [7]:
# 每个大类别下面小类别占比
a = counts1.set_index(['type'])
b = counts1.groupby('type').sum()
c = pd.merge(a,b,left_index=True,right_index=True)
c

        index   num_x   num_y
type
101    101001    5603  411665
101    101002    7776  411665
101    101003  396612  411665
101    101004     125  411665
101    101005      63  411665
101    101006     107  411665
101    101007     147  411665
101    101008     378  411665
101    101009     854  411665
102    102001    2129   17357
102    102002   12021   17357
102    102003    1235   17357
102    102004     361   17357
102    102005     271   17357
102    102006     184   17357
102    102007     538   17357
102    102008     404   17357
102    102009     214   17357
103    103002     189    1715
103    103003    1526    1715
106    106001    3957    3957
107    107001  182900  182900
199   1999001  201426  201426
301    301001   18430   18430

In [8]:
c['persentage'] = (c['num_x']/c['num_y'])*100
del c['num_y']
c.rename(columns={'num_x':'num'},inplace=True)
c

        index     num  persentage
type
101    101001    5603    1.361058
101    101002    7776    1.888915
101    101003  396612   96.343386
101    101004     125    0.030364
101    101005      63    0.015304
101    101006     107    0.025992
101    101007     147    0.035709
101    101008     378    0.091822
101    101009     854    0.207450
102    102001    2129   12.265945
102    102002   12021   69.257360
102    102003    1235    7.115285
102    102004     361    2.079853
102    102005     271    1.561330
102    102006     184    1.060091
102    102007     538    3.099614
102    102008     404    2.327591
102    102009     214    1.232932
103    103002     189   11.020408
103    103003    1526   88.979592
106    106001    3957  100.000000
107    107001  182900  100.000000
199   1999001  201426  100.000000
301    301001   18430  100.000000

In [9]:
c.reset_index(inplace = True)
d = c.sort_values(by=['type','persentage'],ascending=[True,False]).reset_index()
d

    level_0 type    index     num  persentage
0         2  101   101003  396612   96.343386
1         1  101   101002    7776    1.888915
2         0  101   101001    5603    1.361058
3         8  101   101009     854    0.207450
4         7  101   101008     378    0.091822
5         6  101   101007     147    0.035709
6         3  101   101004     125    0.030364
7         5  101   101006     107    0.025992
8         4  101   101005      63    0.015304
9        10  102   102002   12021   69.257360
10        9  102   102001    2129   12.265945
11       11  102   102003    1235    7.115285
12       15  102   102007     538    3.099614
13       16  102   102008     404    2.327591
14       12  102   102004     361    2.079853
15       13  102   102005     271    1.561330
16       17  102   102009     214    1.232932
17       14  102   102006     184    1.060091
18       19  103   103003    1526   88.979592
19       18  103   103002     189   11.020408
20       20  106   106001    3957  100.000000
21       21  107   107001  182900  100.000000
22       22  199  1999001  201426  100.000000
23       23  301   301001   18430  100.000000

In [10]:

del d['level_0']
per_counts= d.set_index(['type','index'])
#保存的表名命名格式为“1_1_k+此表功能名称”，此表表示生成的第2张表格，功能为type_counts_per，计算每个大类下各个小分支所占比例
per_counts.to_excel('1_1_2type_counts_per.xlsx')
per_counts

                 num  persentage
type index
101  101003   396612   96.343386
     101002     7776    1.888915
     101001     5603    1.361058
     101009      854    0.207450
     101008      378    0.091822
     101007      147    0.035709
     101004      125    0.030364
     101006      107    0.025992
     101005       63    0.015304
102  102002    12021   69.257360
     102001     2129   12.265945
     102003     1235    7.115285
     102007      538    3.099614
     102008      404    2.327591
     102004      361    2.079853
     102005      271    1.561330
     102009      214    1.232932
     102006      184    1.060091
103  103003     1526   88.979592
     103002      189   11.020408
106  106001     3957  100.000000
107  107001   182900  100.000000
199  1999001  201426  100.000000
301  301001    18430  100.000000

In [11]:
#-----* 2 *----- 统计知识类型（107类别）内部的点击情况

# 因为只有107001一类，但是可以继续细分成三类：知识内容页、知识列表页、知识首页
def count107(i): #自定义统计函数
    j = i[['fullURL']][i['fullURLId'].str.contains('107')].copy() #找出类别包含107的网址
    j['type'] = None # 添加空列
    j['type'][j['fullURL'].str.contains('info/.+?/')]= u'知识首页'
    j['type'][j['fullURL'].str.contains('info/.+?/.+?')]= u'知识列表页'
    j['type'][j['fullURL'].str.contains('/\d+?_*\d+?\.html')]= u'知识内容页'
    return j['type'].value_counts()
# 注意：获取一次sql对象就需要重新访问一下数据库(!!!)
engine = create_engine('mysql+pymysql://root:@127.0.0.1:3306/jing?charset=utf8')
sql = pd.read_sql('all_gzdata', engine, chunksize = 10000)

counts2 = [count107(i) for i in sql] # 逐块统计
counts2 = pd.concat(counts2).groupby(level=0).sum() # 合并统计结果
counts2

知识内容页    164243
知识列表页      9656
知识首页       9001
Name: type, dtype: int64

In [12]:
#计算各个部分的占比
res107 = pd.DataFrame(counts2)
# res107.reset_index(inplace=True)
res107.index.name= u'107类型'
res107.rename(columns={'type':'num'},inplace=True)
res107[u'百分比'] = (res107['num']/res107['num'].sum())*100
res107.reset_index(inplace = True)
#保存的表名命名格式为“1_1_k+此表功能名称”，此表表示生成的第3张表格，功能为type107，计算知识类型各个小类型所占比例
res107.to_excel('1_1_3type107.xlsx')
res107

   107类型     num        百分比
0  知识内容页  164243  89.799344
1  知识列表页    9656   5.279388
2   知识首页    9001   4.921268

In [13]:
#-----* 3 *----- 统计带"?"问号网址类型统计

# 注意获取一次sql对象就需要重新访问一下数据库

def countquestion(i): #自定义统计函数
    j = i[['fullURLId']][i['fullURL'].str.contains('\?')].copy() #找出类别包含107的网址
    return j

engine = create_engine('mysql+pymysql://root:@127.0.0.1:3306/jing?charset=utf8')
sql = pd.read_sql('all_gzdata', engine, chunksize = 10000)

counts3 = [countquestion(i)['fullURLId'].value_counts() for i in sql]
counts3 = pd.concat(counts3).groupby(level=0).sum()
counts3

101003        47
102002        25
107001       346
1999001    64718
301001       356
Name: fullURLId, dtype: int64

In [14]:
# 求各个类型的占比并保存数据
df1 =  pd.DataFrame(counts3)
df1['perc'] = df1['fullURLId']/df1['fullURLId'].sum()*100
df1.sort_values(by='fullURLId',ascending=False,inplace=True)
#保存的表名命名格式为“1_1_k+此表功能名称”，此表表示生成的第4张表格，功能为questiontype，计算所有带问号页面各个类型的占比
df1.round(4).to_excel('1_1_4questiontype.xlsx')
df1.round(4)

         fullURLId     perc
1999001      64718  98.8182
301001         356   0.5436
107001         346   0.5283
101003          47   0.0718
102002          25   0.0382

In [15]:
# 求带问号的结果占所有数据的比例
from __future__ import division
allcount = counts1['num'].sum()#所有记录总数
df1['fullURLId'].sum()/allcount*100 #7.820407188488865

7.820407188488865

In [16]:
#-----* 4 *----- 统计199类型中的具体类型占比

def page199(i): #自定义统计函数
    j = i[['fullURL','pageTitle']][(i['fullURLId'].str.contains('199')) & (i['fullURL'].str.contains('\?'))]
    j['pageTitle'].fillna(u'空',inplace=True)
    j['type'] = u'其他' # 添加空列
    j['type'][j['pageTitle'].str.contains(u'法律快车-律师助手')]= u'法律快车-律师助手'
    j['type'][j['pageTitle'].str.contains(u'咨询发布成功')]= u'咨询发布成功'
    j['type'][j['pageTitle'].str.contains(u'免费发布法律咨询' )] = u'免费发布法律咨询'
    j['type'][j['pageTitle'].str.contains(u'法律快搜')] = u'快搜'
    j['type'][j['pageTitle'].str.contains(u'法律快车法律经验')] = u'法律快车法律经验'
    j['type'][j['pageTitle'].str.contains(u'法律快车法律咨询')] = u'法律快车法律咨询'
    j['type'][(j['pageTitle'].str.contains(u'_法律快车')) | (j['pageTitle'].str.contains(u'-法律快车'))] = u'法律快车'
    j['type'][j['pageTitle'].str.contains(u'空')] = u'空'
    
    return j
# 注意：获取一次sql对象就需要重新访问一下数据库
engine = create_engine('mysql+pymysql://root:@127.0.0.1:3306/jing?charset=utf8')
sql = pd.read_sql('all_gzdata', engine, chunksize = 10000)# 分块读取数据库信息

counts4 = [page199(i) for i in sql] # 逐块统计
counts4 = pd.concat(counts4)
d1 = counts4['type'].value_counts()
print d1
d2 = counts4[counts4['type']==u'其他']
savetosql(d2,'199elsePercentage')# 将199的网页中的“其他”类型的数据存到数据库中

法律快车-律师助手    49894
法律快车法律咨询      6421
咨询发布成功        5220
快搜            1943
法律快车           818
其他             359
法律快车法律经验        59
空                4
Name: type, dtype: int64

D:\Anaconda2\lib\site-packages\sqlalchemy\engine\default.py:470: Warning: Incorrect string value: '\xD6\xD0\xB9\xFA\xB1\xEA...' for column 'VARIABLE_VALUE' at row 480
  cursor.execute(statement, parameters)
D:\Anaconda2\lib\site-packages\pandas\io\sql.py:1168: UserWarning: The provided table name '199elsePercentage' is not found exactly as such in the database after writing the table, possibly due to case sensitivity issues. Consider using lower case table names.
  warnings.warn(msg, UserWarning)

In [17]:
# 求各个部分的占比并保存数据
df1_ =  pd.DataFrame(d1)
df1_['perc'] = df1_['type']/df1_['type'].sum()*100
df1_.sort_values(by='type',ascending=False,inplace=True)
#保存的表名命名格式为“1_1_k+此表功能名称”，此表表示生成的第5张表格，功能为page199，计算199类型中的具体类型占比
df1_.to_excel('1_1_5page199.xlsx')
df1_

            type       perc
法律快车-律师助手  49894  77.094471
法律快车法律咨询    6421   9.921506
咨询发布成功      5220   8.065762
快搜          1943   3.002256
法律快车         818   1.263945
其他           359   0.554714
法律快车法律经验      59   0.091165
空              4   0.006181

In [18]:
#-----* 5 *----- 统计瞎逛用户中各个类型占比（没有具体的网页以.html后缀结尾）

def xiaguang(i): #自定义统计函数
    j = i[['fullURL','fullURLId','pageTitle']][(i['fullURL'].str.contains('\.html'))==False]
    return j

# 注意获取一次sql对象就需要重新访问一下数据库
engine = create_engine('mysql+pymysql://root:@127.0.0.1:3306/jing?charset=utf8')
sql = pd.read_sql('all_gzdata', engine, chunksize = 10000)# 分块读取数据库信息

counts5 = [xiaguang(i) for i in sql]
counts5 = pd.concat(counts5)

# 将瞎逛的值保存到数据库表中
savetosql(counts5,'xiaguang')# 将199的网页中的“其他”类型的数据存到数据库中

xg1 = counts5['fullURLId'].value_counts()
xg1

1999001    117124
107001      17843
102002      12021
101001       5603
106001       3957
102001       2129
102003       1235
301001       1018
101009        854
102007        538
102008        404
101008        378
102004        361
102005        271
102009        214
102006        184
101004        125
101006        107
101005         63
Name: fullURLId, dtype: int64

In [19]:
# 求各个部分的占比并保存数据
xg_ =  pd.DataFrame(xg1)
xg_.reset_index(inplace=True)
xg_.columns= ['index', 'num']
xg_['perc'] = xg_['num']/xg_['num'].sum()*100
xg_.sort_values(by='num',ascending=False,inplace=True)

xg_['type'] = xg_['index'].str.extract('(\d{3})') #提取前三个数字作为类别id    

xgs_ = xg_[['type', 'num']].groupby('type').sum() #按类别合并
xgs_.sort_values(by='num', ascending=False,inplace=True) #降序排列
xgs_['percentage'] = xgs_['num']/xgs_['num'].sum()*100

#保存的表名命名格式为“1_1_k+此表功能名称”，此表表示生成的第6张表格，功能为xiaguang，计算瞎逛用户中各个类型占比
xgs_.round(4).to_excel('1_1_6xiaguang.xlsx')
xgs_.round(4)

D:\Anaconda2\lib\site-packages\ipykernel_launcher.py:8: FutureWarning: currently extract(expand=None) means expand=False (return Index/Series/DataFrame) but in a future version of pandas this will be changed to expand=True (return DataFrame)

         num  percentage
type
199   117124     71.2307
107    17843     10.8515
102    17357     10.5559
101     7130      4.3362
106     3957      2.4065
301     1018      0.6191